'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {getLocalDesigns,type LocalDesign} from '@/lib/local-designs';
export default function CompareSaved(){
const [items,setItems]=useState<{item:LocalDesign;url:string}[]>([]);const [pin,setPin]=useState(0);const [other,setOther]=useState(0);const [mode,setMode]=useState<'split'|'grid'>('split');
useEffect(()=>{let urls:string[]=[];getLocalDesigns().then(all=>{const originals=all.filter(x=>!x.parentId);if(!originals.length)return;const latest=originals[originals.length-1];const group=originals.filter(x=>x.project?.name===latest.project?.name && Math.abs(x.createdAt-latest.createdAt)<20*60*1000);const ordered=group.slice(-6);setItems(ordered.map(item=>{const url=URL.createObjectURL(item.image);urls.push(url);return {item,url}}));setOther(ordered.length>1?1:0)});return()=>urls.forEach(URL.revokeObjectURL)},[]);
const alternatives=items.map((_,i)=>i).filter(i=>i!==pin);const right=alternatives[other%Math.max(1,alternatives.length)]??pin;
const tile=(i:number)=><div className="overflow-hidden rounded-2xl border border-stone-200 bg-white"><img src={items[i].url} alt={items[i].item.style} className="w-full aspect-[4/3] object-cover"/><div className="p-3"><b>{items[i].item.style}</b><div className="flex flex-wrap gap-2 mt-2"><button className="btn-soft text-sm" onClick={()=>{setPin(i);setOther(0)}}>Pin</button><Link className="btn-primary text-sm" href={'/local-result?id='+encodeURIComponent(items[i].item.id)}>Choose & edit</Link></div></div></div>;
return <main className="max-w-6xl mx-auto p-3 space-y-5"><h1 className="text-3xl font-semibold">Compare your designs</h1><p className="text-stone-600">Your saved designs on this device. Select a design to edit, or pin one to compare.</p>{!items.length?<div className="card p-6">No saved comparison found on this device. <Link className="underline" href="/new-project">Upload a room</Link></div>:<><div className="flex gap-2"><button className="btn-soft" onClick={()=>setMode('grid')}>Grid</button><button className="btn-soft" onClick={()=>setMode('split')}>Pin & swipe</button></div>{mode==='grid'?<div className="grid grid-cols-2 md:grid-cols-3 gap-3">{items.map((_,i)=><div key={items[i].item.id}>{tile(i)}</div>)}</div>:<><div className="grid grid-cols-2 gap-2">{tile(pin)}{items.length>1&&tile(right)}</div>{items.length>1&&<div className="flex justify-between items-center gap-3"><button className="btn-soft" onClick={()=>setOther(v=>(v-1+alternatives.length)%alternatives.length)}>← Previous</button><span className="text-sm">{other%alternatives.length+1} / {alternatives.length}</span><button className="btn-soft" onClick={()=>setOther(v=>(v+1)%alternatives.length)}>Next →</button></div>}</>}</>}<Link className="underline block" href="/new-project">New room</Link></main>
}