import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import { redirect } from 'next/navigation';
import ManageBilling from '@/components/ManageBilling';
import { billingReady } from '@/lib/stripe';

export default async function Page(){
 const demo=!process.env.NEXT_PUBLIC_SUPABASE_URL||!process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
 if(demo){
   return <div><div className="flex justify-between items-start gap-4 mb-8"><div><span className="chip">Demo mode</span><h1 className="text-3xl font-semibold mt-4">Dashboard</h1><p className="text-stone-600 mt-2">Your live demo is running. Connect Supabase later to enable real accounts, saved rooms and credit balances.</p></div><Link href="/new-project" className="btn-primary">New design</Link></div><div className="grid md:grid-cols-3 gap-4"><div className="card p-6"><p className="text-sm text-stone-500">Sample project</p><h2 className="text-xl font-semibold mt-1">Warm Living Room</h2><p className="text-sm text-stone-600 mt-3">Old Money · Beige & Brown · $2,000</p></div><div className="card p-6"><p className="text-sm text-stone-500">Premium credits</p><h2 className="text-3xl font-semibold mt-1">5</h2><p className="text-sm text-stone-600 mt-3">Sample balance for the demo.</p></div><div className="card p-6"><p className="text-sm text-stone-500">Plan</p><h2 className="text-xl font-semibold mt-1">Free Preview</h2><p className="text-sm text-stone-600 mt-3">Payments are not live yet.</p></div></div></div>
 }
 const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)redirect('/auth');
 const [{data:profile},{data:projects}]=await Promise.all([s.from('profiles').select('*').eq('id',user.id).single(),s.from('projects').select('*').eq('user_id',user.id).order('created_at',{ascending:false})]);
 const included=profile?.subscription_credits||0;const purchased=profile?.purchased_credits||0;const total=included+purchased;const paid=(profile?.plan||'free')!=='free';
 return <div><div className="flex justify-between items-start gap-4 mb-8"><div><h1 className="text-3xl font-semibold">Dashboard</h1><p className="text-stone-600 mt-2">Plan: <b className="capitalize">{profile?.plan||'free'}</b> · {paid?<b>Unlimited basic redesigns</b>:<b>{included} free basic designs left</b>}</p><p className="text-sm text-stone-500 mt-1">{paid?`${total} premium credits available (${included} included + ${purchased} purchased)`:`Premium tools require an upgrade or credit pack.`}</p></div><div className="flex flex-wrap gap-2">{billingReady()&&profile?.stripe_customer_id&&<ManageBilling/>}<Link href="/pricing" className="btn-soft">Plans & add-ons</Link><Link href="/new-project" className="btn-primary">New design</Link></div></div><div className="grid md:grid-cols-3 gap-4">{projects?.length?projects.map(p=><Link href={`/project/${p.id}`} key={p.id} className="card p-6 hover:-translate-y-0.5 transition"><p className="text-sm text-stone-500">{p.room_type}</p><h2 className="text-xl font-semibold mt-1">{p.name}</h2><p className="text-sm text-stone-600 mt-3">{p.style} · {p.color_palette} · ${Number(p.budget).toLocaleString()}</p></Link>):<div className="card p-8 md:col-span-3"><p>No projects yet.</p><Link className="underline" href="/new-project">Create your first room</Link></div>}</div></div>
}
